/*
 * SDG 15 - Life on Land
 * Smart Climate and Wildfire Risk Monitoring System
 */
package solutionca.distsysca;

import generated.grpc.alertservice.AlertServiceGrpc.AlertServiceImplBase;
import generated.grpc.alertservice.IncidentReport;
import generated.grpc.alertservice.IncidentAcknowledgement;
import generated.grpc.alertservice.AlertSubscription;
import generated.grpc.alertservice.AlertNotification;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.time.LocalTime;
import java.util.logging.Logger;

/**
 * AlertService Server
 *
 * Implements the two RPC methods defined in alert_service.proto:
 *   1. reportIncident()    - UNARY RPC
 *   2. subscribeToAlerts() - SERVER STREAMING RPC
 *
 * The class extends AlertServiceImplBase which is generated by protoc
 * from alert_service.proto. This is the same pattern as ZooService1
 * extending ZooService1ImplBase from the class sample.
 */
public class AlertServer extends AlertServiceImplBase {

    private static final Logger logger = Logger.getLogger(AlertServer.class.getName());

    public static void main(String[] args) {

        AlertServer alertServer = new AlertServer();

        int port = 50051;

        try {
            Server server = ServerBuilder.forPort(port)
                    .addService(alertServer)
                    .build()
                    .start();

            logger.info("Server started, listening on " + port);
            System.out.println("***** AlertService Server started, listening on " + port);

            server.awaitTermination();

        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    /**
     * UNARY RPC
     * rpc reportIncident (IncidentReport) returns (IncidentAcknowledgement) {}
     *
     * The client sends ONE IncidentReport to the server.
     * The server processes it, assigns a unique incident ID,
     * determines the severity, assigns an emergency response team,
     * and sends back ONE IncidentAcknowledgement.
     *
     * @param request          - the IncidentReport sent by the client
     * @param responseObserver - used to send the response back to the client
     */
    @Override
    public void reportIncident(IncidentReport request,
            StreamObserver<IncidentAcknowledgement> responseObserver) {

        System.out.println(LocalTime.now() + ": reportIncident() received"
                + " | Region: "   + request.getRegionId()
                + " | Event: "    + request.getEventType()
                + " | Severity: " + request.getSeverity()
                + " | Reporter: " + request.getReporterId());

        // Generate a unique incident ID using the region and current time
        String incidentId = "INC-"
                + request.getRegionId().replace("-", "").toUpperCase()
                + "-" + System.currentTimeMillis();

        // Determine status and assigned team based on severity
        String status;
        String assignedTeam;
        String estimatedArrival;

        if (request.getSeverity().equalsIgnoreCase("CRITICAL")) {
            status            = "ESCALATED";
            assignedTeam      = "National Emergency Response Unit - " + request.getRegionId();
            estimatedArrival  = "8 minutes - PRIORITY DISPATCH";
        } else if (request.getSeverity().equalsIgnoreCase("HIGH")) {
            status            = "LOGGED";
            assignedTeam      = "Regional Rapid Response Team - " + request.getRegionId();
            estimatedArrival  = "15 minutes";
        } else {
            status            = "LOGGED";
            assignedTeam      = "Local Monitoring Unit - " + request.getRegionId();
            estimatedArrival  = "30 minutes";
        }

        // Build the IncidentAcknowledgement response
        IncidentAcknowledgement acknowledgement = IncidentAcknowledgement.newBuilder()
                .setIncidentId(incidentId)
                .setStatus(status)
                .setAssignedTeam(assignedTeam)
                .setEstimatedArrival(estimatedArrival)
                .setMessage(request.getEventType() + " [" + request.getSeverity()
                        + "] logged in " + request.getRegionId()
                        + ". " + assignedTeam + " dispatched.")
                .setLoggedAt(System.currentTimeMillis())
                .build();

        System.out.println(LocalTime.now() + ": reportIncident() sending acknowledgement"
                + " | Incident ID: " + incidentId
                + " | Status: "      + status);

        // Send ONE response back - this is UNARY: one request, one response
        responseObserver.onNext(acknowledgement);
        responseObserver.onCompleted();
    }

    /**
     * SERVER STREAMING RPC
     * rpc subscribeToAlerts (AlertSubscription) returns (stream AlertNotification) {}
     *
     * The client sends ONE AlertSubscription (specifying a region and risk level).
     * The server streams back MANY AlertNotification messages - one per threat detected.
     * The server calls onNext() for each alert, then onCompleted() when done.
     *
     * This simulates a live threat feed - in a real system this would
     * run indefinitely as new sensor data arrives. Here we simulate
     * 5 environmental alerts to demonstrate the streaming behaviour.
     *
     * @param request          - the AlertSubscription sent by the client
     * @param responseObserver - used to stream multiple responses back to the client
     */
    @Override
    public void subscribeToAlerts(AlertSubscription request,
            StreamObserver<AlertNotification> responseObserver) {

        System.out.println(LocalTime.now() + ": subscribeToAlerts() received"
                + " | Subscriber: "    + request.getSubscriberId()
                + " | Region: "        + request.getRegionId()
                + " | Min Risk Level: "+ request.getMinRiskLevel());

        // Simulated environmental alerts for the subscribed region
        // Each row: { event_type, risk_level, temperature, humidity, wind_speed, description }
        String[][] alerts = {
            {"WILDFIRE",      "HIGH",     "47.5", "9.2",  "35.0",
             "Temperature rising rapidly. Dry vegetation detected in northern sector."},
            {"WILDFIRE",      "HIGH",     "49.1", "6.3",  "52.0",
             "Fire front advancing. Wind speed increasing to 52km/h. Road access limited."},
            {"HEATWAVE",      "MEDIUM",   "43.0", "14.5", "28.0",
             "Sustained high temperatures. Soil moisture critically low across Zone B."},
            {"WILDFIRE",      "CRITICAL", "51.3", "4.1",  "61.0",
             "CRITICAL: Fire crossed highway. Immediate evacuation recommended."},
            {"DEFORESTATION", "MEDIUM",   "38.0", "22.0", "18.0",
             "Unusual vegetation loss detected in northern sector. Rangers alerted."}
        };

        // Stream each alert back to the client using onNext()
        // SERVER STREAMING: the server calls onNext() MANY times
        for (String[] alert : alerts) {

            AlertNotification notification = AlertNotification.newBuilder()
                    .setAlertId("ALERT-" + request.getRegionId()
                            + "-" + System.currentTimeMillis())
                    .setRegionId(request.getRegionId())
                    .setEventType(alert[0])
                    .setRiskLevel(alert[1])
                    .setTemperature(Float.parseFloat(alert[2]))
                    .setHumidity(Float.parseFloat(alert[3]))
                    .setWindSpeed(Float.parseFloat(alert[4]))
                    .setDescription(alert[5])
                    .setTimestamp(System.currentTimeMillis())
                    .build();

            System.out.println(LocalTime.now() + ": subscribeToAlerts() streaming alert"
                    + " | Event: "     + alert[0]
                    + " | Risk: "      + alert[1]
                    + " | Temp: "      + alert[2] + "C"
                    + " | Humidity: "  + alert[3] + "%");

            // Send this alert to the subscriber
            responseObserver.onNext(notification);

            // Simulate real-time delay between alerts
            try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        // Signal the client that the stream has ended
        responseObserver.onCompleted();
        System.out.println(LocalTime.now() + ": subscribeToAlerts() stream completed for: "
                + request.getSubscriberId());
    }
}