/*
 * SDG 15 - Life on Land
 * Smart Climate and Wildfire Risk Monitoring System
 */
package solutionca.distsysca;

import generated.grpc.climatesensorservice.ClimateSensorServiceGrpc.ClimateSensorServiceImplBase;
import generated.grpc.climatesensorservice.SensorRequest;
import generated.grpc.climatesensorservice.SensorReading;
import generated.grpc.climatesensorservice.SensorSummary;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Logger;

/**
 * ClimateSensorService Server
 *
 * Implements the two RPC methods defined in climate_sensor_service.proto:
 *   1. getLatestReading()      - UNARY RPC
 *   2. streamSensorReadings()  - CLIENT STREAMING RPC
 *
 * The class extends ClimateSensorServiceImplBase which is generated by
 * protoc from climate_sensor_service.proto. Same pattern as ZooService1
 * extending ZooService1ImplBase from the class sample.
 */
public class ClimateSensorServer extends ClimateSensorServiceImplBase {

    private static final Logger logger = Logger.getLogger(ClimateSensorServer.class.getName());

    public static void main(String[] args) {

        ClimateSensorServer sensorServer = new ClimateSensorServer();

        int port = 50052;

        try {
            Server server = ServerBuilder.forPort(port)
                    .addService(sensorServer)
                    .build()
                    .start();

            logger.info("Server started, listening on " + port);
            System.out.println("***** ClimateSensorService Server started, listening on " + port);

            server.awaitTermination();

        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    /**
     * UNARY RPC
     * rpc getLatestReading (SensorRequest) returns (SensorReading) {}
     *
     * The client sends ONE SensorRequest containing a sensor ID.
     * The server looks up that sensor and sends back ONE SensorReading
     * with the most recent environmental values recorded by that sensor.
     *
     * @param request          - the SensorRequest sent by the client
     * @param responseObserver - used to send the response back to the client
     */
    @Override
    public void getLatestReading(SensorRequest request,
            StreamObserver<SensorReading> responseObserver) {

        System.out.println(LocalTime.now() + ": getLatestReading() received"
                + " | Sensor ID: " + request.getSensorId()
                + " | Region: "    + request.getRegionId());

        // Simulate different sensor readings depending on which sensor is queried
        // Sensors 001-002 are in a high-danger zone, 003-004 are moderate, rest are normal
        float temperature;
        float humidity;
        int   co2Ppm;
        float windSpeed;
        float soilMoisture;
        String batteryStatus;

        String sensorId = request.getSensorId().toUpperCase();

        if (sensorId.contains("001") || sensorId.contains("002")) {
            // Zone A sensors - dangerous wildfire conditions
            temperature   = 44.7f;
            humidity      = 8.3f;
            co2Ppm        = 820;
            windSpeed     = 48.5f;
            soilMoisture  = 9.1f;
            batteryStatus = "GOOD";
        } else if (sensorId.contains("003") || sensorId.contains("004")) {
            // Zone B sensors - moderate conditions
            temperature   = 36.2f;
            humidity      = 22.4f;
            co2Ppm        = 510;
            windSpeed     = 29.0f;
            soilMoisture  = 18.5f;
            batteryStatus = "FULL";
        } else {
            // Other sensors - normal conditions
            temperature   = 28.5f;
            humidity      = 45.0f;
            co2Ppm        = 420;
            windSpeed     = 15.0f;
            soilMoisture  = 35.0f;
            batteryStatus = "FULL";
        }

        // Build the SensorReading response
        SensorReading reading = SensorReading.newBuilder()
                .setSensorId(request.getSensorId())
                .setRegionId(request.getRegionId())
                .setTemperature(temperature)
                .setHumidity(humidity)
                .setCo2Ppm(co2Ppm)
                .setWindSpeed(windSpeed)
                .setSoilMoisture(soilMoisture)
                .setLatitude(6.5244f)
                .setLongitude(3.3792f)
                .setTimestamp(System.currentTimeMillis())
                .setBatteryStatus(batteryStatus)
                .build();

        System.out.println(LocalTime.now() + ": getLatestReading() sending reading"
                + " | Temp: "     + temperature + "C"
                + " | Humidity: " + humidity    + "%"
                + " | CO2: "      + co2Ppm      + "ppm");

        // Send ONE response back - this is UNARY: one request, one response
        responseObserver.onNext(reading);
        responseObserver.onCompleted();
    }

    /**
     * CLIENT STREAMING RPC
     * rpc streamSensorReadings (stream SensorReading) returns (SensorSummary) {}
     *
     * The client streams MANY SensorReading messages to the server.
     * The server collects each one in an ArrayList (same pattern as
     * ZooService1.averageTemperature() collecting doubles into a list).
     * When the client calls onCompleted(), the server computes the
     * full risk analysis and sends back ONE SensorSummary response.
     *
     * @param responseObserver - used to send the single summary response back
     * @return StreamObserver   - returned to the client so it can stream readings in
     */
    @Override
    public StreamObserver<SensorReading> streamSensorReadings(
            StreamObserver<SensorSummary> responseObserver) {

        // The server sets up a new observer that gathers each SensorReading
        // that arrives from the client via onNext(), then calculates the
        // summary and risk assessment once it sees onCompleted().
        // This is the same pattern as ZooService1.averageTemperature()
        // collecting temperatures into an ArrayList until onCompleted().
        return new StreamObserver<SensorReading>() {

            // Collect each incoming reading into this list
            // Same pattern as ZooService1 using ArrayList<Double> list
            ArrayList<SensorReading> readings = new ArrayList<>();

            // Accumulators for computing the summary
            float totalTemperature = 0;
            float maxTemperature   = 0;
            float totalHumidity    = 0;
            float minHumidity      = 100;
            float totalWindSpeed   = 0;
            float totalCo2         = 0;
            int   readingsRejected = 0;
            ArrayList<String> flaggedSensors = new ArrayList<>();

            @Override
            // When a new SensorReading arrives from the client, add it to the list
            // Same as ZooService1 doing list.add(request.getTempValue())
            public void onNext(SensorReading reading) {
                System.out.println(LocalTime.now() + ": streamSensorReadings() received reading #"
                        + (readings.size() + 1)
                        + " | Sensor: "   + reading.getSensorId()
                        + " | Temp: "     + reading.getTemperature() + "C"
                        + " | Humidity: " + reading.getHumidity()    + "%");

                // Reject readings with no sensor ID
                if (reading.getSensorId().isEmpty()) {
                    readingsRejected++;
                    return;
                }

                // Accumulate values for summary
                readings.add(reading);
                totalTemperature += reading.getTemperature();
                totalHumidity    += reading.getHumidity();
                totalWindSpeed   += reading.getWindSpeed();
                totalCo2         += reading.getCo2Ppm();

                if (reading.getTemperature() > maxTemperature) maxTemperature = reading.getTemperature();
                if (reading.getHumidity()    < minHumidity)    minHumidity    = reading.getHumidity();

                // Flag sensors that individually exceed danger thresholds
                if (reading.getTemperature() > 42.0f || reading.getHumidity() < 10.0f) {
                    if (!flaggedSensors.contains(reading.getSensorId())) {
                        flaggedSensors.add(reading.getSensorId());
                    }
                }
            }

            @Override
            public void onError(Throwable t) {
                System.out.println(LocalTime.now() + ": streamSensorReadings() error: " + t.getMessage());
            }

            @Override
            // When there are no more readings coming from the client
            // (the client calls onCompleted() on the stream),
            // calculate the averages, compute the risk assessment,
            // build the SensorSummary and send it back via responseObserver.onNext()
            // Same pattern as ZooService1 computing the mean in onCompleted()
            public void onCompleted() {
                System.out.println(LocalTime.now() + ": streamSensorReadings() stream complete"
                        + " | Total readings received: " + readings.size());

                int saved = readings.size();

                // Compute averages - guard against divide-by-zero
                float avgTemp     = saved > 0 ? totalTemperature / saved : 0;
                float avgHumidity = saved > 0 ? totalHumidity    / saved : 0;
                float avgWind     = saved > 0 ? totalWindSpeed   / saved : 0;
                float avgCo2      = saved > 0 ? totalCo2         / saved : 0;

                // Compute wildfire risk assessment from aggregated readings
                String riskAssessment;
                String riskReasoning;

                if (avgTemp > 42.0f && avgHumidity < 10.0f) {
                    riskAssessment = "CRITICAL - IMMEDIATE ACTION REQUIRED";
                    riskReasoning  = "Avg temp " + avgTemp + "C + avg humidity " + avgHumidity
                            + "% + wind " + avgWind + "km/h = CRITICAL WILDFIRE CONDITIONS";
                } else if (avgTemp > 38.0f && avgHumidity < 20.0f) {
                    riskAssessment = "HIGH RISK";
                    riskReasoning  = "Avg temp " + avgTemp + "C + avg humidity " + avgHumidity
                            + "% indicates HIGH danger of wildfire ignition";
                } else if (avgTemp > 33.0f && avgHumidity < 30.0f) {
                    riskAssessment = "MODERATE RISK";
                    riskReasoning  = "Conditions developing. Monitor closely. Avg temp " + avgTemp + "C";
                } else {
                    riskAssessment = "LOW RISK";
                    riskReasoning  = "Conditions within normal range. Avg temp " + avgTemp + "C";
                }

                // Build the SensorSummary response
                SensorSummary summary = SensorSummary.newBuilder()
                        .setStatus(readingsRejected == 0 ? "SUCCESS" : "PARTIAL_FAILURE")
                        .setReadingsReceived(saved + readingsRejected)
                        .setReadingsSaved(saved)
                        .setReadingsRejected(readingsRejected)
                        .setAvgTemperature(avgTemp)
                        .setMaxTemperature(maxTemperature)
                        .setAvgHumidity(avgHumidity)
                        .setMinHumidity(minHumidity)
                        .setAvgWindSpeed(avgWind)
                        .setAvgCo2Ppm(avgCo2)
                        .setRiskAssessment(riskAssessment)
                        .setRiskReasoning(riskReasoning)
                        .addAllFlaggedSensors(flaggedSensors)
                        .setProcessedAt(System.currentTimeMillis())
                        .build();

                System.out.println(LocalTime.now() + ": streamSensorReadings() sending summary"
                        + " | Risk: " + riskAssessment
                        + " | Avg Temp: " + avgTemp + "C"
                        + " | Flagged sensors: " + flaggedSensors.size());

                // The server calls onNext ONE time only - same as ZooService1
                // calling onNext once after computing the mean
                responseObserver.onNext(summary);

                // The server signals it is finished
                responseObserver.onCompleted();
            }
        };
    }
}